### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by pankratz-sco** [stevenbenner/interfacelift-downloader#16]
Im unsure if it's me doing something wrong, but I keep on getting the below error. Any ideas please?

> interfacelift-downloader 1920x1080
SyntaxError: Unexpected number
    at Object.exports.createScript (vm.js:24:10)
    at REPLServer.defaultEval (repl.js:221:25)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
    at REPLServer.Interface._ttyWrite (readline.js:826:14)
>

**Comment by stevenbenner** [comment]
I can't seem to reproduce this issue. And that stacktrace doesn't seem to include any reference to any files from this project.

Can you tell me what version of node you're running? Run `node --version` in the command line to find out.

Also you might try uninstalling then reinstalling the package. Do a `npm cache clean` before installing the package.

**Comment by pankratz-sco** [comment]
Thanks very much for your help, reinstalling the module fixed it.
