### ISSUE TITLE
Unhandled 'error' event.

### ISSUE THREAD

**Issue by friggityFrankel** [stevenbenner/interfacelift-downloader#23]
This is happens a few seconds after hitting enter in the command prompt (tried different resolutions just to be sure):
```
Searching pages for images...
(The download will begin after the page scan finishes.)
Scanning Page 1...
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Emitted 'error' event on ClientRequest instance at:
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
```

**Comment by stevenbenner** [comment]
This was probably because the web site went offline for a couple years. But it seems to be back online now.

Since this issue is very old now, I'm going to go ahead and close it. But if this issue is still happening for you please reply back and let me know.
